name: Create New Tag

on:
  push:
    branches:
      - main
      - dev

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        MAJOR_STRING_TOKEN: "release:"
        MINOR_STRING_TOKEN: "feat:"
        PATCH_STRING_TOKEN: "fix:"
